### ISSUE TITLE
authentication: none

### ISSUE THREAD

**Issue by djhurio** [openanalytics/shinyproxy-rstudio-ide-demo#5]
Is it possible to run the RStudio without ShinyProxy authentication (`authentication: none`)? The RStudio session does not start for me.

![image](https://user-images.githubusercontent.com/744800/207610994-071cfa1c-8878-4370-b97b-435648d8d41d.png)

It was working with `authentication: simple`.

I have the following configuration.

```
proxy:
  ...
  authentication: none
  ...
  specs:
  - id: rstudio
    display-name: RStudio
    description: RStudio Server in Docker container
    container-image: openanalytics/shinyproxy-rstudio-ide-demo:2021.09.2_382__4.1.2
    container-env:
      DISABLE_AUTH: true
      USER: "#{proxy.userId}"
      WWW_ROOT_PATH: "#{proxy.getRuntimeValue('SHINYPROXY_PUBLIC_PATH')}"
    port: 8787
    container-volumes: [ "/tmp/shinyproxy/#{proxy.userId}:/home/#{proxy.userId}" ]
```
